//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.ServiceVenta {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVenta.ServiceVentasSoap")]
    public interface ServiceVentasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/comprobarSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool comprobarSQL(string campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/comprobarSQL", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> comprobarSQLAsync(string campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaVendedorServ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GUI.ServiceVenta.Vendedor buscaVendedorServ(string rut, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaVendedorServ", ReplyAction="*")]
        System.Threading.Tasks.Task<GUI.ServiceVenta.Vendedor> buscaVendedorServAsync(string rut, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarProductosServ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet consultarProductosServ();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarProductosServ", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> consultarProductosServAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarVentasCompletaServ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet consultarVentasCompletaServ();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarVentasCompletaServ", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> consultarVentasCompletaServAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarProductosDeVenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet consultarProductosDeVenta(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarProductosDeVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> consultarProductosDeVentaAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/filtrarProductoMarcaServ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet filtrarProductoMarcaServ(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/filtrarProductoMarcaServ", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> filtrarProductoMarcaServAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarProductoServ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GUI.ServiceVenta.Producto SeleccionarProductoServ(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarProductoServ", ReplyAction="*")]
        System.Threading.Tasks.Task<GUI.ServiceVenta.Producto> SeleccionarProductoServAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarBoletaCabeceraServ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ingresarBoletaCabeceraServ(GUI.ServiceVenta.Venta_Cabecera vc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarBoletaCabeceraServ", ReplyAction="*")]
        System.Threading.Tasks.Task ingresarBoletaCabeceraServAsync(GUI.ServiceVenta.Venta_Cabecera vc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarBoletaDetalleServ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ingresarBoletaDetalleServ(GUI.ServiceVenta.Venta_Detalle vd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarBoletaDetalleServ", ReplyAction="*")]
        System.Threading.Tasks.Task ingresarBoletaDetalleServAsync(GUI.ServiceVenta.Venta_Detalle vd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ultimaVenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ultimaVenta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ultimaVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ultimaVentaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarStock(int cantidad, int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarStock", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarStockAsync(int cantidad, int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/anularBoleta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void anularBoleta(int numVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/anularBoleta", ReplyAction="*")]
        System.Threading.Tasks.Task anularBoletaAsync(int numVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarPorAdmin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool consultarPorAdmin(string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarPorAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> consultarPorAdminAsync(string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarFiado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ingresarFiado(GUI.ServiceVenta.Cliente_Deuda cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarFiado", ReplyAction="*")]
        System.Threading.Tasks.Task ingresarFiadoAsync(GUI.ServiceVenta.Cliente_Deuda cd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarDeuda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ingresarDeuda(int deudaTotal, string rutCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task ingresarDeudaAsync(int deudaTotal, string rutCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GUI.ServiceVenta.Cliente buscaCliente(string rutCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<GUI.ServiceVenta.Cliente> buscaClienteAsync(string rutCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUltimaVentaCabecera", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarUltimaVentaCabecera(int numVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUltimaVentaCabecera", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarUltimaVentaCabeceraAsync(int numVenta);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Vendedor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idVendedorField;
        
        private string rutField;
        
        private string nombreField;
        
        private string passField;
        
        private int idTipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdVendedor {
            get {
                return this.idVendedorField;
            }
            set {
                this.idVendedorField = value;
                this.RaisePropertyChanged("IdVendedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
                this.RaisePropertyChanged("Pass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
                this.RaisePropertyChanged("IdTipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string nombreField;
        
        private string correoField;
        
        private string direccionField;
        
        private int numeroField;
        
        private int totalDeudaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("Correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TotalDeuda {
            get {
                return this.totalDeudaField;
            }
            set {
                this.totalDeudaField = value;
                this.RaisePropertyChanged("TotalDeuda");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente_Deuda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private int idVentaField;
        
        private int creditoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdVenta {
            get {
                return this.idVentaField;
            }
            set {
                this.idVentaField = value;
                this.RaisePropertyChanged("IdVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Credito {
            get {
                return this.creditoField;
            }
            set {
                this.creditoField = value;
                this.RaisePropertyChanged("Credito");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Venta_Detalle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idVentaField;
        
        private int idProductoField;
        
        private int cantidadField;
        
        private int subtotalField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdVenta {
            get {
                return this.idVentaField;
            }
            set {
                this.idVentaField = value;
                this.RaisePropertyChanged("IdVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("IdProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("Subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Venta_Cabecera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idVentaField;
        
        private int idVendedorField;
        
        private string fechaField;
        
        private string horaField;
        
        private int ivaField;
        
        private int totalNetoField;
        
        private int idEstadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdVenta {
            get {
                return this.idVentaField;
            }
            set {
                this.idVentaField = value;
                this.RaisePropertyChanged("IdVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdVendedor {
            get {
                return this.idVendedorField;
            }
            set {
                this.idVendedorField = value;
                this.RaisePropertyChanged("IdVendedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
                this.RaisePropertyChanged("Hora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Iva {
            get {
                return this.ivaField;
            }
            set {
                this.ivaField = value;
                this.RaisePropertyChanged("Iva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TotalNeto {
            get {
                return this.totalNetoField;
            }
            set {
                this.totalNetoField = value;
                this.RaisePropertyChanged("TotalNeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int IdEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("IdEstado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idProductoField;
        
        private string nombreField;
        
        private int precioUnitarioField;
        
        private int stockField;
        
        private int idFamiliaField;
        
        private string marcaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("IdProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int PrecioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("PrecioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("Stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdFamilia {
            get {
                return this.idFamiliaField;
            }
            set {
                this.idFamiliaField = value;
                this.RaisePropertyChanged("IdFamilia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("Marca");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceVentasSoapChannel : GUI.ServiceVenta.ServiceVentasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceVentasSoapClient : System.ServiceModel.ClientBase<GUI.ServiceVenta.ServiceVentasSoap>, GUI.ServiceVenta.ServiceVentasSoap {
        
        public ServiceVentasSoapClient() {
        }
        
        public ServiceVentasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceVentasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVentasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVentasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool comprobarSQL(string campo) {
            return base.Channel.comprobarSQL(campo);
        }
        
        public System.Threading.Tasks.Task<bool> comprobarSQLAsync(string campo) {
            return base.Channel.comprobarSQLAsync(campo);
        }
        
        public GUI.ServiceVenta.Vendedor buscaVendedorServ(string rut, string pass) {
            return base.Channel.buscaVendedorServ(rut, pass);
        }
        
        public System.Threading.Tasks.Task<GUI.ServiceVenta.Vendedor> buscaVendedorServAsync(string rut, string pass) {
            return base.Channel.buscaVendedorServAsync(rut, pass);
        }
        
        public System.Data.DataSet consultarProductosServ() {
            return base.Channel.consultarProductosServ();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> consultarProductosServAsync() {
            return base.Channel.consultarProductosServAsync();
        }
        
        public System.Data.DataSet consultarVentasCompletaServ() {
            return base.Channel.consultarVentasCompletaServ();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> consultarVentasCompletaServAsync() {
            return base.Channel.consultarVentasCompletaServAsync();
        }
        
        public System.Data.DataSet consultarProductosDeVenta(int num) {
            return base.Channel.consultarProductosDeVenta(num);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> consultarProductosDeVentaAsync(int num) {
            return base.Channel.consultarProductosDeVentaAsync(num);
        }
        
        public System.Data.DataSet filtrarProductoMarcaServ(string filtro) {
            return base.Channel.filtrarProductoMarcaServ(filtro);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> filtrarProductoMarcaServAsync(string filtro) {
            return base.Channel.filtrarProductoMarcaServAsync(filtro);
        }
        
        public GUI.ServiceVenta.Producto SeleccionarProductoServ(string nombre) {
            return base.Channel.SeleccionarProductoServ(nombre);
        }
        
        public System.Threading.Tasks.Task<GUI.ServiceVenta.Producto> SeleccionarProductoServAsync(string nombre) {
            return base.Channel.SeleccionarProductoServAsync(nombre);
        }
        
        public void ingresarBoletaCabeceraServ(GUI.ServiceVenta.Venta_Cabecera vc) {
            base.Channel.ingresarBoletaCabeceraServ(vc);
        }
        
        public System.Threading.Tasks.Task ingresarBoletaCabeceraServAsync(GUI.ServiceVenta.Venta_Cabecera vc) {
            return base.Channel.ingresarBoletaCabeceraServAsync(vc);
        }
        
        public void ingresarBoletaDetalleServ(GUI.ServiceVenta.Venta_Detalle vd) {
            base.Channel.ingresarBoletaDetalleServ(vd);
        }
        
        public System.Threading.Tasks.Task ingresarBoletaDetalleServAsync(GUI.ServiceVenta.Venta_Detalle vd) {
            return base.Channel.ingresarBoletaDetalleServAsync(vd);
        }
        
        public int ultimaVenta() {
            return base.Channel.ultimaVenta();
        }
        
        public System.Threading.Tasks.Task<int> ultimaVentaAsync() {
            return base.Channel.ultimaVentaAsync();
        }
        
        public void actualizarStock(int cantidad, int idProducto) {
            base.Channel.actualizarStock(cantidad, idProducto);
        }
        
        public System.Threading.Tasks.Task actualizarStockAsync(int cantidad, int idProducto) {
            return base.Channel.actualizarStockAsync(cantidad, idProducto);
        }
        
        public void anularBoleta(int numVenta) {
            base.Channel.anularBoleta(numVenta);
        }
        
        public System.Threading.Tasks.Task anularBoletaAsync(int numVenta) {
            return base.Channel.anularBoletaAsync(numVenta);
        }
        
        public bool consultarPorAdmin(string pass) {
            return base.Channel.consultarPorAdmin(pass);
        }
        
        public System.Threading.Tasks.Task<bool> consultarPorAdminAsync(string pass) {
            return base.Channel.consultarPorAdminAsync(pass);
        }
        
        public void ingresarFiado(GUI.ServiceVenta.Cliente_Deuda cd) {
            base.Channel.ingresarFiado(cd);
        }
        
        public System.Threading.Tasks.Task ingresarFiadoAsync(GUI.ServiceVenta.Cliente_Deuda cd) {
            return base.Channel.ingresarFiadoAsync(cd);
        }
        
        public void ingresarDeuda(int deudaTotal, string rutCliente) {
            base.Channel.ingresarDeuda(deudaTotal, rutCliente);
        }
        
        public System.Threading.Tasks.Task ingresarDeudaAsync(int deudaTotal, string rutCliente) {
            return base.Channel.ingresarDeudaAsync(deudaTotal, rutCliente);
        }
        
        public GUI.ServiceVenta.Cliente buscaCliente(string rutCliente) {
            return base.Channel.buscaCliente(rutCliente);
        }
        
        public System.Threading.Tasks.Task<GUI.ServiceVenta.Cliente> buscaClienteAsync(string rutCliente) {
            return base.Channel.buscaClienteAsync(rutCliente);
        }
        
        public void eliminarUltimaVentaCabecera(int numVenta) {
            base.Channel.eliminarUltimaVentaCabecera(numVenta);
        }
        
        public System.Threading.Tasks.Task eliminarUltimaVentaCabeceraAsync(int numVenta) {
            return base.Channel.eliminarUltimaVentaCabeceraAsync(numVenta);
        }
    }
}
